version: '3.8'
services:
  database:
    image: 'postgres:12.4-alpine'
    container_name: 'softserve-node.js-db'
    restart: on-failure
    stop_grace_period: 10s
    environment:
      POSTGRES_USER: 'softserve'
      POSTGRES_PASSWORD: 'softserve'
      POSTGRES_DB: 'training'
    ports:
      - '5432:5432'
    volumes:
      - './docker/var/lib/postgresql/data:/var/lib/postgresql/data'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER']
      interval: 10s
      timeout: 5s
      retries: 3
  database-management:
    image: 'dpage/pgadmin4:latest'
    container_name: 'softserve-node.js-db-manage'
    restart: on-failure
    stop_grace_period: 10s
    environment:
      PGADMIN_DEFAULT_EMAIL: 'nodejs@softserveinc.com'
      PGADMIN_DEFAULT_PASSWORD: 'softserve'
      PGADMIN_LISTEN_PORT: 3333
    ports:
      - '3333:3333'
    depends_on:
      - database
    volumes:
      - './docker/var/lib/pgadmin:/var/lib/pgadmin'
      - './docker/pgadmin4/servers.json:/pgadmin4/servers.json'
